spring.application.name=SpringCsrftokens
spring.security.user.name=Aryan
spring.security.user.password=password

#now these is a method throw which we block the other servers and website to access our sessionId
#we make it directly only accessable to the same website these is called same- site strict

server.servlet.cookie.same-site=strict